import type { Metadata } from "next";
import { PageHeader } from "@/components/page-header";
import { clubBenefits, clubGroups, nonGroupedClubs } from "@/data/campus-life";

export const metadata: Metadata = { title: "Clubs & Societies", description: "Clubs, societies, service groups and student organizations at ANSECO." };

export default function ClubsSocietiesPage() {
  return <div className="bg-[#F8F7F3]"><PageHeader eyebrow="Campus Life" title="Clubs & Societies" description="Student organizations provide opportunities for service, leadership, creativity, faith and shared interests." /><div className="mx-auto max-w-[1160px] space-y-14 px-5 py-20 sm:px-8 lg:px-12"><section><p className="max-w-3xl border-l-4 border-[#C9990A] bg-white p-6 text-base leading-8 text-[#334155]">Students are expected to belong to two clubs: one in Group A and another in Group B.</p><div className="mt-8 overflow-hidden border border-[#0D2E6B]/10 bg-white"><div className="bg-[#0D2E6B] px-5 py-4"><h2 className="text-sm font-black uppercase tracking-[0.16em] text-white">Club Groupings</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] border-collapse text-left text-sm"><thead className="bg-[#EDF1F9] text-[#0D2E6B]"><tr><th className="w-20 px-5 py-3">S/N</th><th className="px-5 py-3">Group A</th><th className="px-5 py-3">Group B</th></tr></thead><tbody className="divide-y divide-[#0D2E6B]/10">{clubGroups.map((club) => <tr key={club.sn}><td className="px-5 py-4 font-black text-[#C9990A]">{club.sn}</td><td className="px-5 py-4 font-semibold text-[#0D2E6B]">{club.groupA}</td><td className="px-5 py-4 text-[#334155]">{club.groupB || "-"}</td></tr>)}</tbody></table></div></div></section><section><h2 className="font-display text-3xl font-bold text-[#0D2E6B]">Other Student Groups</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{nonGroupedClubs.map((club) => <div key={club} className="border border-[#0D2E6B]/10 bg-white px-5 py-4 font-bold text-[#0D2E6B]">{club}</div>)}</div></section><section><h2 className="font-display text-3xl font-bold text-[#0D2E6B]">Benefits of Participation</h2><ol className="mt-6 grid gap-4 lg:grid-cols-2">{clubBenefits.map((benefit, index) => <li key={benefit} className="flex gap-4 bg-white p-5 text-sm leading-7 text-[#334155]"><span className="font-black text-[#C9990A]">{String(index + 1).padStart(2, "0")}</span><span>{benefit}</span></li>)}</ol></section></div></div>;
}
